pipeline {
	agent any

    stages {
		stage('Checkout') {
			steps {
				checkout scm
            }
        }

        stage('Install npm dependencies') {
			steps {
				dir('frontend') {
					sh 'npm install'
                }
            }
        }

        stage('Build frontend') {
			steps {
				dir('frontend') {
					sh 'npm run build'
                }
            }
        }

        stage('Test frontend') {
			steps {
				dir('frontend') {
					sh 'npm run test'
                }
            }
        }

        stage('Sonar report send') {
			steps {
				dir('frontend') {
					withSonarQubeEnv('SonarQube') {
						sh 'npm run test'
						sh 'rm -rf ~/.sonar/cache'
						sh 'npm run sonar'
					}
                }
			}
        }

        stage('Sonar report check') {
			steps {
				dir('frontend') {
					script {
                        def qg = waitForQualityGate()
                        if (qg.status != 'OK') {
                            error "Quality Gate failed: ${qg.status}"
                        }
                    }
				}
			}
		}

        stage('Build and push Docker image') {
			steps {
				dir('frontend') {
					script {
						sh """
                        echo "$DOCKER_PASSWORD_FOR_PUSH" | docker login --username "$DOCKER_USERNAME_FOR_PUSH" --password-stdin
                        docker build -t ivankustarev/devops-2025-frontend:latest .
                        docker push ivankustarev/devops-2025-frontend:latest
                        """
                	}
                }
            }
        }

        stage('Deployment') {
			steps {
				dir('backend') {
					script {
						sh 'kubectl --insecure-skip-tls-verify --server=$K8S_SERVER --client-certificate=/var/jenkins_home/.minikube/profiles/minikube/client.crt --client-key=/var/jenkins_home/.minikube/profiles/minikube/client.key rollout restart deployment devops-2025-frontend'
					}
				}
			}
		}
    }

    post {
		failure {
			echo 'Build failed!'
        }
    }
}
