pipeline {
	agent any

    stages {
		stage('Checkout') {
			steps {
				checkout scm
            }
        }

        stage('Install npm dependencies') {
			steps {
				dir('frontend') {
					sh 'npm install'
                }
            }
        }

        stage('Build frontend') {
			steps {
				dir('frontend') {
					sh 'npm run build'
                }
            }
        }

        stage('Test frontend') {
			steps {
				dir('frontend') {
					sh 'npm run test'
                }
            }
        }

        stage('Sonar report send') {
			steps {
				dir('frontend') {
					withSonarQubeEnv('SonarQube') {
						sh 'npm run test'
						sh 'rm -rf ~/.sonar/cache'
						sh 'npm run sonar'
					}
                }
			}
        }

        stage('Sonar report check') {
			steps {
				dir('frontend') {
					timeout(time: 1, unit: 'MINUTES') {
						script {
							def qg = waitForQualityGate()
                        	if (qg.status != 'OK') {
								error "Quality Gate failed: ${qg.status}"
                        	}
                    	}
                    }
				}
			}
		}

        stage('Build and push Docker image') {
			steps {
				dir('frontend') {
					script {
						sh """
                        echo "$DOCKER_PASSWORD_FOR_PUSH" | docker login --username "$DOCKER_USERNAME_FOR_PUSH" --password-stdin
                        docker build -t ivankustarev/devops-2025-backend:latest .
                        docker push ivankustarev/devops-2025-backend:latest
                        """
                	}
                }
            }
        }
    }

    post {
		failure {
			echo 'Build failed!'
        }
    }
}
