version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "54324:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/your_database_name
      SPRING_DATASOURCE_USERNAME: your_username
      SPRING_DATASOURCE_PASSWORD: your_password

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  jenkins:
    build:
      context: ./jenkins
    ports:
      - "8088:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/jcasc.yaml:/var/jenkins_home/casc.yaml
      - ./jenkins/jobs/pipeline-backend.groovy:/var/jenkins_home/jobs/pipeline-backend.groovy
      - ./jenkins/jobs/pipeline-bot.groovy:/var/jenkins_home/jobs/pipeline-bot.groovy
      - ./jenkins/jobs/pipeline-frontend.groovy:/var/jenkins_home/jobs/pipeline-frontend.groovy
      - ~/.kube:/var/jenkins_home/.kube
      - ~/.minikube:/var/jenkins_home/.minikube
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin
      - DOCKER_USERNAME_FOR_PUSH=${DOCKER_USERNAME}
      - DOCKER_PASSWORD_FOR_PUSH=${DOCKER_PASSWORD}
      - K8S_SERVER=https://host.docker.internal:55932

  bot:
    build:
      context: ./bot
    container_name: bot
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - TELEGRAM_ADMIN_CHAT_ID=${TELEGRAM_ADMIN_CHAT_ID}

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    depends_on:
      - sonarqube-db

  sonarqube-db:
    image: postgres:13
    container_name: sonarqube-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  sonarqube_db_data:
