pipeline {

	agent {
		docker {
			image 'ivankustarev/debian-openjdk-17-maven-3.9.4-docker'
			args '-v /var/run/docker.sock:/var/run/docker.sock'
			args '-e DOCKER_USERNAME_FOR_PUSH'
			args '-e DOCKER_PASSWORD_FOR_PUSH'
			args '--privileged'
        }
    }

    stages {
		stage('Checkout') {
			steps {
				checkout scm
            }
        }

        stage('Build') {
			steps {
				dir('backend') {
					sh 'mvn clean install -DskipTests'
				}
            }
        }

        stage('Test') {
			steps {
				dir('backend') {
					sh 'mvn clean test'
				}
            }
        }

        stage('Push Image') {
			steps {
				dir('backend') {
					script {
						sh """
                        echo "$DOCKER_PASSWORD_FOR_PUSH" | docker login --username "$DOCKER_USERNAME_FOR_PUSH" --password-stdin
                        docker build -t ivankustarev/devops-2025-backend:latest .
                        docker push ivankustarev/devops-2025-backend:latest
                        """
                	}
                }
            }
        }
    }

    post {
		failure {
			echo 'Build failed!'
        }
    }
}