pipeline {

	agent any

	environment {
        SONAR_LOGIN = credentials('sonar-token-id')
    }

    stages {
		stage('Checkout') {
			steps {
				checkout scm
            }
        }

        stage('Build') {
			steps {
				dir('backend') {
					sh 'mvn clean install -DskipTests'
				}
            }
        }

        stage('Test') {
			steps {
				dir('backend') {
					sh 'mvn clean test'
				}
            }
        }

        stage('Sonar') {
			steps {
				dir('backend') {
					withSonarQubeEnv('SonarQube') {
						sh 'mvn clean verify sonar:sonar'
					}

					script {
						def qg = waitForQualityGate()
                        if (qg.status != 'OK') {
							error "Quality Gate failed: ${qg.status}"
                        }
                    }
				}
			}
		}

        stage('Push Image') {
			steps {
				dir('backend') {
					script {
						sh """
                        echo "$DOCKER_PASSWORD_FOR_PUSH" | docker login --username "$DOCKER_USERNAME_FOR_PUSH" --password-stdin
                        docker build -t ivankustarev/devops-2025-backend:latest .
                        docker push ivankustarev/devops-2025-backend:latest
                        """
                	}
                }
            }
        }
    }

    post {
		failure {
			echo 'Build failed!'
        }
    }
}