jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

tool:
  git:
    installations:
      - name: "Default"
        home: "/usr/bin/git"

jobs:
  - file: /var/jenkins_home/jobs/pipeline-frontend.groovy
  - file: /var/jenkins_home/jobs/pipeline-backend.groovy
