apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-2025-bot-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: bot.devops-2025
      http:
        paths:
          - path: /bot
            pathType: Prefix
            backend:
              service:
                name: devops-2025-bot
                port:
                  number: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: bot
spec:
  selector:
    app: devops-2025-bot
  ports:
    - port: 8081
      targetPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-2025-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-2025-bot
  template:
    metadata:
      labels:
        app: devops-2025-bot
    spec:
      containers:
        - name: devops-2025-bot
          image: ivankustarev/devops-2025-bot:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: TELEGRAM_BOT_TOKEN
              value: 1821081337:AAFPL5N7_aH7_EEuDU6g73VB50GxeEF0-jc
            - name: TELEGRAM_BOT_USERNAME
              value: the47iqtestbot
            - name: TELEGRAM_ADMIN_CHAT_ID
              value: '574871067'
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
