---
- name: Установка Docker и Docker Compose
  hosts: all
  become: yes

  vars:
    docker_packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
    docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    docker_compose_version: "v2.24.6"

  tasks:
    - name: Установка зависимостей
      apt:
        name: "{{ docker_packages }}"
        state: present
        update_cache: yes

    - name: Добавление GPG-ключа Docker
      apt_key:
        url: "{{ docker_gpg_url }}"
        state: present

    - name: Добавление Docker-репозитория
      apt_repository:
        repo: "{{ docker_repo }}"
        state: present
        filename: docker

    - name: Установка Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes

    - name: Включение и запуск службы Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Загрузка Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-$(uname -s)-$(uname -m)"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Создание символической ссылки на docker-compose (если нужно)
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
        force: yes

    - name: Проверка версии Docker
      command: docker --version
      register: docker_version_output
      changed_when: false

    - name: Проверка версии Docker Compose
      command: docker-compose --version
      register: compose_version_output
      changed_when: false
